### Notes: 



# french class: 
https://m2dsupsdlclass.github.io/lectures-labs/

notes on back-prop. derivations: 

https://www.kamperh.com/notes/kamper_backprop17.pdf

detailed implementation in python: forward and backward passes: 
        
http://neuralnetworksanddeeplearning.com/chap2.html

In [ ]:

# this is very important; 
# size specifies only one dimension 
# so numpy creates a vector; 
# e.g. (3, 1) is still treated as a matrix and affects MUL
# but (3, ) is a vector!
# so the following is wrong
# bias = np.random.uniform(low=low, high=high, size=(number_of_neurons, 1))
# but this is correct:

bias = np.random.uniform(low=low, high=high, size=(number_of_neurons, ))

In [1]:
import numpy as np

In [9]:
x = np.array([1, 2, 3])

In [10]:
x.dot(x)

14

In [11]:
x.T.dot(x)

14

In [12]:
y = np.atleast_2d(x)

In [13]:
y

array([[1, 2, 3]])

In [17]:
y.dot(y)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [15]:
y.T.dot(y)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [16]:
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Dropout:

https://m2dsupsdlclass.github.io/lectures-labs/slides/03_recommender_systems/index.html#36
    
    
p36:
    
The nodes in the figure represent activation function; output of a node is y; which is multiplied by w (represented as a weight of an edges), and it goes as an input x^{next} = W y to the next node, i.e. the activation function at the next level.

Dropout is a probability of the node-removal; with which we individually remove **nodes** and incident edges! Dropout is not the probability of the edge-removal!
    

# add links: 

https://en.wikipedia.org/wiki/Norm_(mathematics)

In [ ]:
lect 3; p35